name: 'azure-fetch'

on:
  workflow_dispatch:
  # disabled
  # push:
  #   branches: [ master ]
  # schedule:
  #   - cron: '15 */12 * * *'

jobs:
  fetch-posts:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - name: fetch post
        shell: bash
        env:
          LEANCLOUD_APP_ID: ${{ secrets.LEANCLOUD_APP_ID }}
          LEANCLOUD_APP_KEY: ${{ secrets.LEANCLOUD_APP_KEY }}
          LEANCLOUD_MASTER_KEY: ${{ secrets.LEANCLOUD_MASTER_KEY }}
          COSMOS_CONNECTION_URI: ${{ secrets.COSMOS_CONNECTION_URI }}
          TZ: 'Asia/Shanghai'
        run: |
          node db/azure/curd.js --action fetch
