name: 'newsletter'

on:
  workflow_dispatch:
  schedule:
    - cron: '2 0 * * *'

jobs:
  send-mail:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm i
      - name: 'Set Args'
        run: |
            echo "TZ=Asia/Shanghai" >> $GITHUB_ENV
            echo "HTML_OUTPUT=result.html" >> $GITHUB_ENV
            echo "TEXT_OUTPUT=result.txt" >> $GITHUB_ENV
            echo "POST_DATE=$(TZ=':Asia/Shanghai' date --date=' 1 days ago' '+%Y%m%d')" >> $GITHUB_ENV
      - shell: bash
        env:
          LEANCLOUD_APP_ID: ${{ secrets.LEANCLOUD_APP_ID }}
          LEANCLOUD_APP_KEY: ${{ secrets.LEANCLOUD_APP_KEY }}
          LEANCLOUD_MASTER_KEY: ${{ secrets.LEANCLOUD_MASTER_KEY }}
        run: |
          node actions/newsletter.js --day ${{ env.POST_DATE }} --htmloutput ${{ env.HTML_OUTPUT }} --textoutput ${{ env.TEXT_OUTPUT }}
          cat ${{ env.HTML_OUTPUT }}
          cat ${{ env.TEXT_OUTPUT }}
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3.0.0
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: (${{env.POST_DATE}}) Hot Posts
          body: file://${{ env.TEXT_OUTPUT }}
          html_body: file://${{ env.HTML_OUTPUT }}
          to: v2ex@groups.io,v2ex_hot_posts@googlegroups.com
          # to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions
