name: 'v2ex-mail'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm i
      - shell: bash
        env:
          LEANCLOUD_APP_ID: ${{ secrets.LEANCLOUD_APP_ID }}
          LEANCLOUD_APP_KEY: ${{ secrets.LEANCLOUD_APP_KEY }}
          LEANCLOUD_MASTER_KEY: ${{ secrets.LEANCLOUD_MASTER_KEY }}
          GIT_SHA: ${{ github.sha }}
          TZ: 'Asia/Shanghai'
        run: |
          node actions/hacker-news/mail.js result.html
          node actions/v2ex/mail.js result.html
          cat result.html
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: (${{env.REPORT_DATE}}) Hot Posts
          body: file://result.html
          to: v2ex@groups.io,v2ex_hot_posts@googlegroups.com,v2ex_hot_posts@groups.163.com
          # to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions
          content_type: text/html
